citizenscience/user/models.py
# -*- coding: utf-8 -*-

from sqlalchemy import Column, desc
from sqlalchemy.orm import backref

from werkzeug.security import generate_password_hash, check_password_hash

from flask_login import UserMixin

from citizenscience.extensions import db
from citizenscience.utils import get_current_time
from citizenscience.constants import USER, USER_ROLE, ADMIN, INACTIVE, USER_STATUS, \
    SEX_TYPES, STRING_LEN


class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = Column(db.Integer, primary_key=True)
    name = Column(db.String(STRING_LEN), nullable=False, unique=True)
    email = Column(db.String(STRING_LEN), nullable=False, unique=True)
    phone = Column(db.String(STRING_LEN), nullable=False, default="")
    url = Column(db.String(STRING_LEN), nullable=False, default="")
    deposit = Column(db.Numeric, nullable=False, default=0.0)
    location = Column(db.String(STRING_LEN), nullable=False, default="")
    bio = Column(db.Text, default="")
    activation_key = Column(db.String(STRING_LEN))
    create_at = Column(db.DateTime, nullable=False, default=get_current_time)
    update_at = Column(db.DateTime)

    avatar = Column(db.String(STRING_LEN))

    _password = Column('password', db.String(200), nullable=False)

    def _get_password(self):
        return self._password

    def _set_password(self, password):
        self._password = generate_password_hash(password)

    # Hide password encryption by exposing password field only.
    password = db.synonym('_password',
                          descriptor=property(_get_password,
                                              _set_password))

    def check_password(self, password):
        if self.password is None:
            return False
        return check_password_hash(self.password, password)

    _sex = Column('sex', db.Integer, nullable=False, default=1)

    def _get_sex(self):
        return SEX_TYPES.get(self.sex)

    def _set_sex(self, sex):
        self._sex = sex

    sex = db.synonym('_sex', descriptor=property(_get_sex, _set_sex))

    # ================================================================
    role_code = Column(db.SmallInteger, default=USER, nullable=False)

    @property
    def role(self):
        return USER_ROLE[self.role_code]

    def is_admin(self):
        return self.role_code == ADMIN

    # ================================================================
    # One-to-many relationship between users and user_statuses.
    status_code = Column(db.SmallInteger, nullable=False, default=INACTIVE)

    @property
    def status(self):
        return USER_STATUS[self.status_code]

    # ================================================================
    # Class methods

    @classmethod
    def authenticate(cls, login, password):
        user = cls.query.filter(db.or_(
            User.name == login, User.email == login)).first()

        if user:
            authenticated = user.check_password(password)
        else:
            authenticated = False

        return user, authenticated

    @classmethod
    def search(cls, keywords):
        criteria = []
        for keyword in keywords.split():
            keyword = '%' + keyword + '%'
            criteria.append(db.or_(
                User.name.ilike(keyword),
                User.email.ilike(keyword),
            ))
        q = reduce(db.and_, criteria)
        return cls.query.filter(q)

    @classmethod
    def get_by_id(cls, user_id):
        return cls.query.filter_by(id=user_id).first_or_404()

    def check_name(self, name):
        return User.query.filter(db.and_(
            User.name == name, User.email != self.id)).count() == 0

citizenscience/user/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from flask_wtf.html5 import URLField, EmailField, TelField

from wtforms import ValidationError, StringField, PasswordField, SubmitField, \
    TextAreaField, FileField, DateField, SelectField
from wtforms.validators import DataRequired, Length, EqualTo, Email, URL, \
    AnyOf, Optional
from flask_login import current_user

from citizenscience.user import User
from citizenscience.constants import PASSWORD_LEN_MIN, PASSWORD_LEN_MAX, SEX_TYPES, \
    BIO_TIP, ALLOWED_AVATAR_EXTENSIONS
from citizenscience.utils import allowed_file


class ProfileForm(Form):
    email = EmailField('Email', [DataRequired(), Email()])
    # Don't use the same name as model because we are going to use populate_obj().
    # avatar_file = FileField("Avatar", [Optional()])
    phone = TelField('Phone', [DataRequired(), Length(max=64)])
    url = URLField('URL', [Optional(), URL()])
    location = StringField('Location', [Optional(), Length(max=64)])
    bio = TextAreaField('Bio', [Optional(), Length(max=1024)],
                        description=BIO_TIP)
    submit = SubmitField('Update profile',
                         render_kw={"class": "btn btn-success"})

    def validate_name(form, field):
        user = User.get_by_id(current_user.id)
        if not user.check_name(field.data):
            raise ValidationError("Please pick another name.")

    def validate_avatar_file(form, field):
        if field.data and not allowed_file(field.data.filename):
            raise ValidationError("Please upload files with extensions: %s" %
                                  "/".join(ALLOWED_AVATAR_EXTENSIONS))


class PasswordForm(Form):
    password = PasswordField('Current password', [DataRequired()])
    new_password = PasswordField('New password',
                                 [DataRequired(),
                                  Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)])
    password_again = PasswordField('Password again',
                                   [DataRequired(),
                                    Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX),
                                    EqualTo('new_password')])
    submit = SubmitField('Update password')

    def validate_password(form, field):
        user = User.get_by_id(current_user.id)
        if not user.check_password(field.data):
            raise ValidationError("Password is wrong.")

citizenscience/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from flask import Blueprint, render_template, current_app, request, flash, \
    url_for, redirect, session, abort
from flask_login import login_required, login_user, current_user, logout_user, \
    confirm_login, login_fresh

from citizenscience.user import User
from citizenscience.extensions import db, login_manager
from forms import SignupForm, LoginForm, RecoverPasswordForm, ReauthForm, \
    ChangePasswordForm


from pymongo import MongoClient
import json
from bson import json_util
from bson.json_util import dumps

MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
DBS_NAME = 'citizenscience'

COLLECTION_GBF = 'gbf'
GBF_FIELDS = {'_id': 0,
'Group_ID': 1, 'Monitor_ID': 1, 'Site_ID':1, 'Site_Description':1,
'Latitude':1, 'Longitude':1, 'Sample_Date':1, 'Sample_Time':1, 'Sample_Depth_m': 1,
'Air_Temp_degC': 1, 'Water_Temp_degC': 1, 'Avg_DO': 1, 'pH': 1, 'Transparency_m': 1,
'Total_Depth_m': 1, 'Flow': 1, 'Algae': 1, 'Color': 1, 'Clarity': 1, 'Surface': 1,
'Conditions': 1, 'Odor': 1, 'Weather': 1, 'Days_Since_Precip': 1, 'Rain_Accum': 1,
'Expired_Reagent': 1, 'Enterococcus': 1, 'Specific_Gravity': 1, 'SpGr_Temp': 1,
'Salinity': 1, 'Tide': 1, 'Comments': 1, 'Area': 1, 'Correct_Time': 1, 'Date_Time': 1}

COLLECTION_NACD = 'nacd'
NACD_FIELDS = {'_id': 0,
'No': 1, 'Site_ID':1, 'Site': 1, 'Latitude':1, 'Longitude':1, 'Sample_Date':1,
'Sample_Time':1, 'Monitor_ID': 1, 'Participants': 1, 'Land_Use': 1, 'AirTemp_C': 1,
'Wind_Speed_mph': 1, 'Wind_Direction': 1,  'Tide_stage': 1, 'Weather': 1,
'WaterTemp_C': 1, 'Salinity_ppt': 1, 'Turbidity_NTU': 1, 'pH': 1, 'DissolvedOxygen_ppm': 1,
'Nitrates_ppm': 1, 'Litter_kg': 1, 'Most_Abundant_Litter': 1, 'Most_Abundant_Species': 1,
'Species_Found': 1, 'Date_Time': 1}


def get_db():
    c = MongoClient()
    return c.citizenscience

frontend = Blueprint('frontend', __name__)

@frontend.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))
    return render_template('index.html')


@frontend.route('/citizenscience2')
def index_alt():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))
    return render_template('index.html')


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash("Logged in", 'success')
            return redirect(form.next.data or url_for('user.profile'))
        else:
            flash('Sorry, invalid login', 'danger')

    return render_template('frontend/login.html', form=form)


@frontend.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            flash('Reauthenticated.', 'success')
            return redirect('/change_password')

        flash('Password is wrong.', 'danger')
    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        if login_user(user):
            flash('Signed up', 'success')
            return redirect(form.next.data or url_for('user.profile'))

    return render_template('frontend/signup.html', form=form)


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    user = None
    if current_user.is_authenticated:
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(activation_key=user.activation_key)

    if form.validate_on_submit():
        user.password = form.password.data
        user.activation_key = None
        db.session.add(user)
        db.session.commit()

        flash("Your password has been changed, please log in again", "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on '
                  'how to access your account', 'success')

            user.activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash('Sorry, no user found for that email address', 'error')

    return render_template('frontend/reset_password.html', form=form)

# Error handler
@frontend.errorhandler(404)
def handle_404(err):
    return render_template('errors/404.html'), 404


@frontend.errorhandler(500)
def handle_500(err):
    return render_template('errors/500.html'), 500


@frontend.route('/gbf_db')
def gbf_db():
    return render_template('projects/gbf_dashboard.html')


@frontend.route('/gbf_db/data')
def gbf_data():
    connection = MongoClient(MONGODB_HOST, MONGODB_PORT)
    collection = connection[DBS_NAME][COLLECTION_GBF]
    #projects = collection.find(fields=FIELDS, limit=50000)
    projects = collection.find({}, GBF_FIELDS)
    json_projects = []
    for project in projects:
        json_projects.append(project)

    json_projects = json.dumps(json_projects)
    geojson_projects = write_to_geojson(json_projects)
    return geojson_projects


@frontend.route('/nacd_db')
def nacd_db():
    return render_template('projects/nacd_dashboard.html')


@frontend.route('/nacd_db/data')
def nacd_data():
    db = get_db()
    projects = db.nacd.find()
    json_projects = []
    for project in projects:
        json_projects.append(project)
    json_projects = json.dumps(json_projects, default=json_util.default)
    geojson_projects = write_to_geojson(json_projects)
    return geojson_projects


def write_to_geojson(items):
    return json.dumps({
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature",
            "geometry": {
                "type": 'Point',
                "coordinates": [feature['Longitude'], feature['Latitude']]},
                "properties": {key: value
                    for key, value in feature.items()
                    #if key not in ('Latitude', 'Longitude')
                }
            }
        for feature in json.loads(items)
        ]
    })

citizenscience/user/__init__.py
# -*- coding: utf-8 -*-

from models import User
from views import user

citizenscience/user/views.py
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, render_template, send_from_directory, request, \
    current_app, flash
from flask_login import login_required, current_user

from forms import ProfileForm, PasswordForm

from citizenscience.extensions import db
from citizenscience.utils import get_current_time


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/<int:user_id>/avatar/<path:filename>')
@login_required
def avatar(user_id, filename):
    dir_path = os.path.join(
        current_app.config['UPLOAD_FOLDER'], 'user_%s' % user_id)
    return send_from_directory(dir_path, filename, as_attachment=True)


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(user)
        user.update_at = get_current_time()

        db.session.commit()

        flash('Public profile updated.', 'success')

    return render_template('user/profile.html', form=form)


@user.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    form = PasswordForm()

    if form.validate_on_submit():
        form.populate_obj(user)
        user.password = form.new_password.data

        db.session.commit()

        flash('Password updated.', 'success')

    return render_template('user/password.html', form=form)

citizenscience/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Cache-control" content="public">
    <title>{% block title %}{{ page_title }}{% endblock %} - Citizen Science</title>
    <meta name="description" content="Citizen Science for the Gulf of Mexico. The project is being developed as the outreach and education portion of the developing GCOOS Integrated Water Quality Network">
    <meta name="author" content="Shin Kobara - GCOOS">
    <!-- To ensure proper rendering and touch zooming, add the viewport meta tag to your <head>. -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">

    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/jquery-ui/themes/base/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!-- Base Map CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/leaflet/dist/leaflet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Leaflet.awesome-markers/dist/leaflet.awesome-markers.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Leaflet.defaultextent/dist/leaflet.defaultextent.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/leaflet.locatecontrol/dist/L.Control.Locate.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/leaflet.markercluster/dist/MarkerCluster.Default.css') }}">
    {% endblock %}

    {% block css_additional %}{% endblock %}

</head>

<body class="application">
    {% include "macros/_ask_user_to_update_ie.html" %} {% block topbar %}
    <div class='container'>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-icon-container">
                        <a href="#" class="navbar-icon pull-right visible-xs" id="nav-btn"><i class="fa fa-bars fa-lg white"></i></a> {% block sidepanel %} {% endblock %}
                    </div>
                    <a class="navbar-brand" href="{{ url_for('frontend.index') }}">Citizen Science</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href='{{ url_for("frontend.index") }}'><i class="fa fa-map-marker white"></i>&nbsp;&nbsp;Home</a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" id="downloadDrop" href="#" role="button" data-toggle="dropdown"><i class="fa fa-cloud-download white"></i>&nbsp;&nbsp;Get Data<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href='{{ url_for("frontend.gbf_db") }}'><i class="fa fa-download"></i>&nbsp;&nbsp;Galveston Bay Foundation</a>
                                </li>
                                <li><a href='{{ url_for("frontend.nacd_db") }}'><i class="fa fa-download"></i>&nbsp;&nbsp;Nature's Academy</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="about-btn"><i class="fa fa-info-circle white"></i>&nbsp;&nbsp;About</a>
                        </li>
                        <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="help-btn"><i class="fa fa-question-circle white"></i>&nbsp;&nbsp;Help</a>
                        </li>

                        <li>
                            <a href="http://gcoos.org/products"><img src='{{ url_for("static", filename="images/logo/gcoos_50.png") }}' style='height:30px; margin-top:-10px;' /></a>
                        </li>
                    </ul>
                    {% block additional_nav %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block flash_message %}
    <div class="container-fluid">
        {% with messages = get_flashed_messages(with_categories=True) %} {% if messages %}
        <div class="container-fluid">
            <div id='flash_message_container'>
                {% for category, msg in messages %}
                <div class="alert alert-{{ category }}">
                    <button type="button" class="close" data-dismiss="alert">×</button> {{ msg }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %} {% endwith %}
    </div>
    {% endblock %}

    {% block container %}
      {% block bodycontents %}{% endblock %}
      {% block about_modal %}{% endblock %}
      {% block help_modal %}{% endblock %}
    {% endblock %}

    <footer>
    </footer>

    {% block extra %} {% endblock %}

    {% block js_btm %}
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/d3/d3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/d3-queue/d3-queue.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/moment/min/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/togeojson/togeojson.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/leaflet/dist/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/esri-leaflet/dist/esri-leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/Leaflet.awesome-markers/dist/leaflet.awesome-markers.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/Leaflet.defaultextent/dist/leaflet.defaultextent.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/leaflet.locatecontrol/dist/L.Control.Locate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/leaflet.markercluster/dist/leaflet.markercluster.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/leaflet-spin/leaflet.spin.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bower_components/spin.js/spin.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}

    {% block js_addition %} {% endblock %}

    {% block ga %} {% include "macros/_analytics.html" %} {% endblock %}
</body>

</html>

citizenscience/templates/layouts/user.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="row">
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading clearfix">
                <b>{{ current_user.name }}</b>
			</div>
			<div class="panel-body">
				<ul class="nav nav-pills nav-stacked">
					<li role="presentation" class="{% if request.endpoint == 'user.profile' %}active{% endif %}">
						<a href="{{ url_for('user.profile') }}">Profile</a>
					</li>
                    <li role="presentation" class="{% if request.endpoint == 'user.password' %}active{% endif %}">
						<a href="{{ url_for('user.password') }}">Password</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
    <div class="col-md-9">
		{% block panel_right %}
		{% endblock %}
	</div>
</div>
{% endblock %}